### ISSUE TITLE
Speed up parsing

### ISSUE THREAD

**Issue by benton-anderson** [lifs-tools/csgoslin#15]
@dominik-kopczynski  @nilshoffmann 

Why does LipidParser().parse() take on average 0.3 seconds to parse simple strings like"TG 18:1_16:1_18:2"? 0.3 seconds is the average without profiling or debug mode. 

Code is simple: 
```
var parser = new LipidParser();
var parsed = parser.parse("TG 18:1_16:1_18:2");
```

Line-by-line profiling shows thousands of recursive calls to collect_backwards. What's going on? 
![image](https://user-images.githubusercontent.com/31827732/215143895-4b019475-0212-4d79-87c4-37765fed5ea5.png)

I would like to incorporate csgoslin into our lipidomics software, but if parsing 300 Identified lipids takes 100 seconds then this is likely untenable.

**Comment by nilshoffmann** [comment]
Hi, the 0.3 seconds are most likely attributable to the initialization effort for the six parsers running behind LipidParser (constant overhead). Please note that you should therefor not create a new instance for every parse, but rather create a new instance once and then apply the 'parse' method with each new lipid name to receive a new LipidAdduct object with each invocation, if you supply a different argument. If that still does not solve the speed issue for you, please ping me back.

The parser is based on a generic, recursive parsing method (therefor, you see the repeated calls to collect_backwards) which is used in all our language-specific implementations to avoid different behaviour from subtle implementation differences.

**Comment by benton-anderson** [comment]
Hi Nils,

Yes, that solved my problem. Thank you very much for the quick response. 

Ben
